services:
  web:
    build:
      context: .
      args:
        VITE_SITE_URL: ${VITE_SITE_URL:-http://localhost:4173}
    image: awesome-web-components
    container_name: afu-awesome-web-components
    ports:
      - "4173:80"
    restart: unless-stopped
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true